// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiupC28AXu8QflaDwp97EaoWcNzcPxBjM',
    appId: '1:982960331422:web:cb3b5fcdf228e10391f98f',
    messagingSenderId: '982960331422',
    projectId: 'wallpeper-643f1',
    authDomain: 'wallpeper-643f1.firebaseapp.com',
    storageBucket: 'wallpeper-643f1.appspot.com',
    measurementId: 'G-VQN5RCSR4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR8UQeLCBS8JB2h14-R3uajpVQqDQ83sA',
    appId: '1:982960331422:android:90040e93b6db3b3291f98f',
    messagingSenderId: '982960331422',
    projectId: 'wallpeper-643f1',
    storageBucket: 'wallpeper-643f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkLi_O0n_KIf4lu5Kne3aTcct2FgG3AgQ',
    appId: '1:982960331422:ios:0754d0566e3145ba91f98f',
    messagingSenderId: '982960331422',
    projectId: 'wallpeper-643f1',
    storageBucket: 'wallpeper-643f1.appspot.com',
    iosBundleId: 'com.example.techWallpaper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkLi_O0n_KIf4lu5Kne3aTcct2FgG3AgQ',
    appId: '1:982960331422:ios:0754d0566e3145ba91f98f',
    messagingSenderId: '982960331422',
    projectId: 'wallpeper-643f1',
    storageBucket: 'wallpeper-643f1.appspot.com',
    iosBundleId: 'com.example.techWallpaper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiupC28AXu8QflaDwp97EaoWcNzcPxBjM',
    appId: '1:982960331422:web:4069930cf24202da91f98f',
    messagingSenderId: '982960331422',
    projectId: 'wallpeper-643f1',
    authDomain: 'wallpeper-643f1.firebaseapp.com',
    storageBucket: 'wallpeper-643f1.appspot.com',
    measurementId: 'G-Q6E053WT3J',
  );
}
